<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Two Input Fields_sum1</name>
   <tag></tag>
   <elementGuidId>05d47cae-e6bf-4552-bafe-996291b2e95a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sum1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sum1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Please enter first value&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a5954ab-6469-4a89-9b2c-8f8233486332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b124593a-c08a-4705-96cb-9b2cd5baefc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-550 w-full h-35 rounded px-10</value>
      <webElementGuid>da49e1f3-3c0b-4622-b419-105c1d35102d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter first value</value>
      <webElementGuid>bcfe47aa-babe-4edd-9349-c48eeeccc1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sum1</value>
      <webElementGuid>7f33e8ba-0721-4b4d-b2b3-f96c82025231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sum1&quot;)</value>
      <webElementGuid>8e4f2ae7-8f75-4fc8-b4d9-8f2b0d4a564f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sum1']</value>
      <webElementGuid>93585648-839a-4fea-8396-3714af244097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gettotal']/input</value>
      <webElementGuid>f9067a6f-7b2a-493a-bf7d-d8934471449e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/input</value>
      <webElementGuid>f32899a5-3683-413c-9140-93fd10214550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Please enter first value' and @id = 'sum1']</value>
      <webElementGuid>3c829dcd-882b-4c02-a51c-d094f2d384d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
