<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Two Input Fields_sum2</name>
   <tag></tag>
   <elementGuidId>c0685914-6e8c-415a-a428-a66be5d3cbfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sum2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sum2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Please enter second value&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>851ec644-0d31-427a-a9ea-b195d950d2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d0ddda5f-6645-40aa-92e0-e9ddbe52d421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-gray-550 w-full h-35 rounded px-10</value>
      <webElementGuid>549f5ca3-a028-40ec-a381-4b8a365f6b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter second value</value>
      <webElementGuid>6353033b-3048-48a7-9ee5-e72b908b7c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sum2</value>
      <webElementGuid>1befd7c4-c530-4312-bc59-f3cf6f7490e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sum2&quot;)</value>
      <webElementGuid>3698ec7d-8715-43a6-92c4-183c3f49d1ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sum2']</value>
      <webElementGuid>4817d9bd-47e5-4328-9329-a4f9cc252d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gettotal']/input[2]</value>
      <webElementGuid>abadaed2-b873-4d42-b297-91e190e8a29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>70f0a6a8-a0d3-4a8c-a79f-00de757cef69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Please enter second value' and @id = 'sum2']</value>
      <webElementGuid>e7d16082-6d57-462d-a647-90912bbeb46a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
