<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Test</name>
   <tag></tag>
   <elementGuidId>a7dbb68f-9d39-4edb-ba6c-7de0e8c9dd83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Test&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8899f06e-7932-427e-a61b-75ca4264996e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>037f9e11-acea-466c-a77b-b8f39937c312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-20</value>
      <webElementGuid>070904eb-45b6-4009-a28a-65025b6d164e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>f257a296-3990-4527-89e0-f2d66e1f9c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;message&quot;)</value>
      <webElementGuid>2307ebdd-69c3-47c2-8678-62f870141cc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='message']</value>
      <webElementGuid>febb1f40-2d51-4c4c-b5f0-a35305759aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-message']/p</value>
      <webElementGuid>4593a4ed-7fe8-47a0-af60-98a8a6e6240f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Message:'])[1]/following::p[1]</value>
      <webElementGuid>c5fd3cdb-e39e-40e7-9312-b7d5aec5ef7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Checked Value'])[1]/following::p[1]</value>
      <webElementGuid>e61abb53-4f91-412f-b6e2-335bd176b8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Two Input Fields'])[1]/preceding::p[1]</value>
      <webElementGuid>be870307-eb31-4c91-9eaa-cdf6093df704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Sum'])[1]/preceding::p[3]</value>
      <webElementGuid>8acd9477-3697-40ac-9902-03d9f59172c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test']/parent::*</value>
      <webElementGuid>0ee0b96c-6f99-4b86-892d-469d9266e000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/p</value>
      <webElementGuid>58d454be-04be-4c8e-9661-c81539c38975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'message' and (text() = 'Test' or . = 'Test')]</value>
      <webElementGuid>01099d89-6763-4b93-9186-dc357c2fc9db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
