<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Test Message</name>
   <tag></tag>
   <elementGuidId>8860f9ae-45ec-4186-99d4-ab0c972acc6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Test Message&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>adec73e5-1ec1-46ed-9c38-69c144d1053d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>f18017fa-bb24-4050-92ea-e8a5bb1dc8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-20</value>
      <webElementGuid>40e6975a-67ac-4aa2-a581-f647dd6a2225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Message</value>
      <webElementGuid>8951460f-9449-42c7-a4fa-ca0b9d8ee7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;message&quot;)</value>
      <webElementGuid>66e5a047-e832-4761-9b5d-22f4370a2da4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='message']</value>
      <webElementGuid>cead3c3f-d30b-4395-a471-f4ca23e4a5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-message']/p</value>
      <webElementGuid>2b7d1408-39e0-4006-bced-cf0109bd26d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Message:'])[1]/following::p[1]</value>
      <webElementGuid>bbddea22-a295-4f5d-84f2-5b7de18564f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Checked Value'])[1]/following::p[1]</value>
      <webElementGuid>d9d8d714-e663-42d6-9efc-b555e099fd1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Two Input Fields'])[1]/preceding::p[1]</value>
      <webElementGuid>c3d3ef45-d142-4925-a8fb-8d005a0786f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Sum'])[1]/preceding::p[3]</value>
      <webElementGuid>8b18de77-ebdb-40a7-8c7b-97f36707a53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test Message']/parent::*</value>
      <webElementGuid>6e9f39c2-31c6-4b5c-a1cf-a6007291fbc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/p</value>
      <webElementGuid>488482d9-bd85-4a9c-9242-6ae03428385e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'message' and (text() = 'Test Message' or . = 'Test Message')]</value>
      <webElementGuid>93651bc8-6df9-4688-87f4-ad79b1a1ee89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
